#!/usr/bin/env python

Import('env')
Import('env_modules')

# Thirdparty source files

env_sproto = env_modules.Clone()

#if (env["sproto"] != "system"): # builtin
thirdparty_dir = "#thirdparty/sproto/"
thirdparty_sources = [
	"sproto.c",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_sproto.add_source_files(env.modules_sources, thirdparty_sources)
env_sproto.Append(CPPPATH = [thirdparty_dir])

env_sproto.add_source_files(env.modules_sources,"*.cpp")

Export('env')